# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pseudometer',
                'doc_host': 'https://sbavery.github.io',
                'git_url': 'https://github.com/sbavery/pseudometer',
                'lib_path': 'pseudometer'},
  'syms': {'pseudometer.core': {'pseudometer.core.foo': ('core.html#foo', 'pseudometer/core.py')}}}