# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_confidence.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_confidence.ipynb 3
import warnings
warnings.filterwarnings('ignore')
import requests
from bs4 import BeautifulSoup
import enchant
import re
import random
from collections import Counter
from fastai.text.all import *
from .data import *
import hashlib
import pickle

from sklearn.svm import OneClassSVM
from sklearn.feature_extraction.text import TfidfVectorizer
